# Generated by Django 4.2.1 on 2023-05-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=300)),
                ('college', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=300)),
                ('college', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='vhse',
            new_name='engineering',
        ),
        migrations.RenameModel(
            old_name='others',
            new_name='finearts',
        ),
        migrations.RenameModel(
            old_name='computerscience',
            new_name='journalism',
        ),
    ]
